const icons = {
  area: require('../../assets/icons/area.png'),
  backArrow: require('../../assets/icons/back-arrow.png'),
  bath: require('../../assets/icons/bath.png'),
  bed: require('../../assets/icons/bed.png'),
  bell: require('../../assets/icons/bell.png'),
  calendar: require('../../assets/icons/calendar.png'),
  carPark: require('../../assets/icons/car-park.png'),
  chat: require('../../assets/icons/chat.png'),
  cutlery: require('../../assets/icons/cutlery.png'),
  dog: require('../../assets/icons/dog.png'),
  dumbell: require('../../assets/icons/dumbell.png'),
  edit: require('../../assets/icons/edit.png'),
  filter: require('../../assets/icons/filter.png'),
  google: require('../../assets/icons/google.png'),
  heart: require('../../assets/icons/heart.png'),
  home: require('../../assets/icons/home.png'),
  info: require('../../assets/icons/info.png'),
  language: require('../../assets/icons/language.png'),
  laundry: require('../../assets/icons/laundry.png'),
  location: require('../../assets/icons/location.png'),
  logout: require('../../assets/icons/logout.png'),
  people: require('../../assets/icons/people.png'),
  person: require('../../assets/icons/person.png'),
  phone: require('../../assets/icons/phone.png'),
  rightArrow: require('../../assets/icons/right-arrow.png'),
  run: require('../../assets/icons/run.png'),
  search: require('../../assets/icons/search.png'),
  send: require('../../assets/icons/send.png'),
  shield: require('../../assets/icons/shield.png'),
  star: require('../../assets/icons/star.png'),
  swim: require('../../assets/icons/swim.png'),
  wallet: require('../../assets/icons/wallet.png'),
  wifi: require('../../assets/icons/wifi.png'),
};

export default icons;
